-- MySQL Script generated by MySQL Workbench
-- Tue May 21 23:23:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Players` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Players` (
  `player_Name` VARCHAR(255) NOT NULL,
  `player_Note` LONGTEXT NULL,
  PRIMARY KEY (`player_Name`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ships` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ships` (
  `ship_Name` VARCHAR(255) NOT NULL,
  `ship_Type` VARCHAR(2) NULL,
  PRIMARY KEY (`ship_Name`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Player_has_Ships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Player_has_Ships` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Player_has_Ships` (
  `Players_player_Name` VARCHAR(255) NOT NULL,
  `Ships_ship_Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Players_player_Name`, `Ships_ship_Name`),
  INDEX `fk_Players_has_Ships_Ships1_idx` (`Ships_ship_Name` ASC) VISIBLE,
  INDEX `fk_Players_has_Ships_Players_idx` (`Players_player_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Players_has_Ships_Players`
    FOREIGN KEY (`Players_player_Name`)
    REFERENCES `Players` (`player_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Players_has_Ships_Ships1`
    FOREIGN KEY (`Ships_ship_Name`)
    REFERENCES `Ships` (`ship_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
