openapi: 3.0.0
info:
  title: WoWS Clan Battle Tool Backend
  version: 0.0.1
  description: A Backend for the WoWS Clan Battle Tool
servers:
  - url: http://localhost:8080/
    description: Local development server
paths:
  /:
    get:
      responses:
        200:
          description: OK
